source_image            = "Deep Learning Driver AMI GPU (Ubuntu 20.04)"
instance_type           = "g4dn.2xlarge"
arch                    = "amd64"
nvidia_major_version    = "510"
script                  = "setup_without_nvidia.sh"
image_owner             = "898082745236"
gr_oss_image_name       = "gross-cuda-nvidia-ghrunner"